In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/amazon_products_sales_data_cleaned.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2408 entries, 0 to 2407
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_title         2408 non-null   object
 1   product_rating        2406 non-null   float64
 2   total_reviews         2406 non-null   float64
 3   purchased_last_month  2025 non-null   float64
 4   discounted_price      2317 non-null   float64
 5   original_price        2317 non-null   float64
 6   is_best_seller        2408 non-null   object
 7   is_sponsored          2408 non-null   object
 8   has_coupon            2408 non-null   object
 9   buy_box_availability  1686 non-null   object
 10  delivery_date         1760 non-null   object
 11  sustainability_tags   378 non-null    object
 12  product_image_url     2408 non-null   object
 13  product_page_url      2231 non-null   object
 14  data_collected_at     2407 non-null   object
 15  product_category      2407 non-null   object
 16  discount_percentage   2316 non-null   float64
dtypes: float64(6), object(11)
memory usage: 319.9+ KB

In [ ]:
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [ ]:
df.tail()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
2403,"UGREEN USB-C Bluetooth Adapter for PS5, Blueto...",4.4,1084.0,2000.0,22.99,29.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61Hd-cVZsz...,https://www.amazon.com/UGREEN-Bluetooth-aptX-A...,2025-08-21 11:32:34,Phones,23.34
2404,Microsoft Surface Pro 2-in-1 Laptop/Tablet (20...,4.4,600.0,300.0,929.00,1199.99,No Badge,Organic,No Coupon,Add to cart,2025-09-02,Energy efficiency,https://m.media-amazon.com/images/I/617kakTyb3...,https://www.amazon.com/Microsoft-Surface-Windo...,2025-08-21 11:32:34,Laptops,22.58
2405,"Sennheiser HD 280 Pro Headphone, Black",4.5,12307.0,1000.0,84.29,84.29,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61+XjHbWrZ...,https://www.amazon.com/Sennheiser-280-Pro-Head...,2025-08-21 11:32:34,Phones,0.00
2406,"Crucial 64GB DDR5 RAM Kit (2x32GB), 4800MHz CL...",4.8,6091.0,500.0,139.96,199.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61O5IUjSDS...,https://www.amazon.com/Crucial-2x32GB-4800MHz-...,2025-08-21 11:32:34,Laptops,30.02
2407,"SABRE 120 dB Wedge Door Stop Security Alarm, E...",4.4,6765.0,2000.0,12.49,14.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61HQzV1nC-...,https://www.amazon.com/SABRE-Wedge-Security-Al...,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2408 entries, 0 to 2407
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_title         2408 non-null   object
 1   product_rating        2406 non-null   float64
 2   total_reviews         2406 non-null   float64
 3   purchased_last_month  2025 non-null   float64
 4   discounted_price      2317 non-null   float64
 5   original_price        2317 non-null   float64
 6   is_best_seller        2408 non-null   object
 7   is_sponsored          2408 non-null   object
 8   has_coupon            2408 non-null   object
 9   buy_box_availability  1686 non-null   object
 10  delivery_date         1760 non-null   object
 11  sustainability_tags   378 non-null    object
 12  product_image_url     2408 non-null   object
 13  product_page_url      2231 non-null   object
 14  data_collected_at     2407 non-null   object
 15  product_category      2407 non-null   object
 16  discount_percentage   2316 non-null   float64
dtypes: float64(6), object(11)
memory usage: 319.9+ KB

In [ ]:
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [ ]:
df.shape

(2408, 17)

In [ ]:
df.columns

Index(['product_title', 'product_rating', 'total_reviews',
       'purchased_last_month', 'discounted_price', 'original_price',
       'is_best_seller', 'is_sponsored', 'has_coupon', 'buy_box_availability',
       'delivery_date', 'sustainability_tags', 'product_image_url',
       'product_page_url', 'data_collected_at', 'product_category',
       'discount_percentage'],
      dtype='object')

In [ ]:
df.loc[0:1,"product_title":"product_rating"]

                                       product_title  product_rating
0  BOYA BOYALINK 2 Wireless Lavalier Microphone f...             4.6
1  LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...             4.3

In [ ]:
df.loc[0:2,"product_title":"total_reviews"]

,product_title,product_rating,total_reviews
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0

In [ ]:
df.iloc[0:3,0:3]

,product_title,product_rating,total_reviews
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0

In [ ]:
df.isnull().sum()

product_title              0
product_rating             2
total_reviews              2
purchased_last_month     383
discounted_price          91
original_price            91
is_best_seller             0
is_sponsored               0
has_coupon                 0
buy_box_availability     722
delivery_date            648
sustainability_tags     2030
product_image_url          0
product_page_url         177
data_collected_at          1
product_category           1
discount_percentage       92
dtype: int64

In [ ]:
df.dropna()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
10,Amazon Basics 48-Pack AA Alkaline High-Perform...,4.7,865598.0,100000.0,14.99,14.99,Best Seller,Organic,No Coupon,Add to cart,2025-08-29,Safer chemicals +1 more,https://m.media-amazon.com/images/I/81iJ+tnLAD...,https://www.amazon.com/AmazonBasics-Performanc...,2025-08-21 11:14:29,Laptops,0.00
14,"Peak Design Slide Lite Camera Strap, Black, Co...",4.7,7235.0,500.0,69.95,69.95,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,Small Business,https://m.media-amazon.com/images/I/61wslWB9gB...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Cameras,0.00
16,"Amazon Basics Multipurpose Copy Printer Paper,...",4.8,198512.0,80000.0,39.97,39.97,Best Seller,Organic,No Coupon,Add to cart,2025-09-01,1 sustainability certification,https://m.media-amazon.com/images/I/71QiYj-N8P...,https://www.amazon.com/AmazonBasics-Bright-Mul...,2025-08-21 11:14:29,Printers & Scanners,0.00
17,Amazon Basics AAA Alkaline High-Performance Ba...,4.7,625776.0,100000.0,14.49,14.49,Best Seller,Organic,No Coupon,Add to cart,2025-08-29,Safer chemicals +1 more,https://m.media-amazon.com/images/I/81Apg8B6+0...,https://www.amazon.com/Amazon-Basics-AAA-High-...,2025-08-21 11:14:29,Laptops,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2352,"Peak Design Slide Lite Camera Strap, Black, Co...",4.7,7235.0,500.0,69.95,69.95,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,Small Business,https://m.media-amazon.com/images/I/61wslWB9gB...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:32:12,Cameras,0.00
2358,"ASUS 23.8”1080P Monitor(VA24DQSB)-Full HD,IPS,...",4.6,2149.0,400.0,139.00,139.00,No Badge,Organic,No Coupon,Add to cart,2025-09-01,Energy efficiency +3 more,https://m.media-amazon.com/images/I/71eMcVIzfI...,https://www.amazon.com/ASUS-23-8-1080P-Monitor...,2025-08-21 11:32:23,Laptops,0.00
2367,Brother Monochrome Laser Printer with 32 PPM S...,3.9,510.0,800.0,134.99,134.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,Energy efficiency,https://m.media-amazon.com/images/I/71Y+m8BdZC...,https://www.amazon.com/Brother-HL-L2400D-Monoc...,2025-08-21 11:32:23,Printers & Scanners,0.00
2396,"Peak Design Slide Lite Camera Strap, Black, Co...",4.7,7235.0,500.0,69.95,69.95,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,Small Business,https://m.media-amazon.com/images/I/61wslWB9gB...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:32:34,Cameras,0.00
2404,Microsoft Surface Pro 2-in-1 Laptop/Tablet (20...,4.4,600.0,300.0,929.00,1199.99,No Badge,Organic,No Coupon,Add to cart,2025-09-02,Energy efficiency,https://m.media-amazon.com/images/I/617kakTyb3...,https://www.amazon.com/Microsoft-Surface-Windo...,2025-08-21 11:32:34,Laptops,22.58

In [ ]:
df.dropna().sum()

product_title           BOYA BOYALINK 2 Wireless Lavalier Microphone f...
product_rating                                                     1007.8
total_reviews                                                   4170567.0
purchased_last_month                                             981450.0
discounted_price                                                 25755.72
original_price                                                   30327.47
is_best_seller          No BadgeBest SellerNo BadgeBest SellerBest Sel...
is_sponsored            SponsoredOrganicSponsoredOrganicOrganicOrganic...
has_coupon              Save 15%  with couponNo CouponNo CouponNo Coup...
buy_box_availability    Add to cartAdd to cartAdd to cartAdd to cartAd...
delivery_date           2025-09-012025-08-292025-08-292025-09-012025-0...
sustainability_tags     Carbon impactSafer chemicals +1 moreSmall Busi...
product_image_url       https://m.media-amazon.com/images/I/71pAqiVEs3...
product_page_url        https://www.amazon.com/sspa/click?ie=UTF8&spc=...
data_collected_at       2025-08-21 11:14:292025-08-21 11:14:292025-08-...
product_category        PhonesLaptopsCamerasPrinters & ScannersLaptops...
discount_percentage                                               2733.18
dtype: object

In [ ]:
df.fillna(2)

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,2,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,2,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,2,2,2,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,2,2,2,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2403,"UGREEN USB-C Bluetooth Adapter for PS5, Blueto...",4.4,1084.0,2000.0,22.99,29.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,2,https://m.media-amazon.com/images/I/61Hd-cVZsz...,https://www.amazon.com/UGREEN-Bluetooth-aptX-A...,2025-08-21 11:32:34,Phones,23.34
2404,Microsoft Surface Pro 2-in-1 Laptop/Tablet (20...,4.4,600.0,300.0,929.00,1199.99,No Badge,Organic,No Coupon,Add to cart,2025-09-02,Energy efficiency,https://m.media-amazon.com/images/I/617kakTyb3...,https://www.amazon.com/Microsoft-Surface-Windo...,2025-08-21 11:32:34,Laptops,22.58
2405,"Sennheiser HD 280 Pro Headphone, Black",4.5,12307.0,1000.0,84.29,84.29,No Badge,Organic,No Coupon,2,2,2,https://m.media-amazon.com/images/I/61+XjHbWrZ...,https://www.amazon.com/Sennheiser-280-Pro-Head...,2025-08-21 11:32:34,Phones,0.00
2406,"Crucial 64GB DDR5 RAM Kit (2x32GB), 4800MHz CL...",4.8,6091.0,500.0,139.96,199.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,2,https://m.media-amazon.com/images/I/61O5IUjSDS...,https://www.amazon.com/Crucial-2x32GB-4800MHz-...,2025-08-21 11:32:34,Laptops,30.02
2407,"SABRE 120 dB Wedge Door Stop Security Alarm, E...",4.4,6765.0,2000.0,12.49,14.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,2,https://m.media-amazon.com/images/I/61HQzV1nC-...,https://www.amazon.com/SABRE-Wedge-Security-Al...,2,2,2.00

In [ ]:
df.columns

Index(['product_title', 'product_rating', 'total_reviews',
       'purchased_last_month', 'discounted_price', 'original_price',
       'is_best_seller', 'is_sponsored', 'has_coupon', 'buy_box_availability',
       'delivery_date', 'sustainability_tags', 'product_image_url',
       'product_page_url', 'data_collected_at', 'product_category',
       'discount_percentage'],
      dtype='object')

In [ ]:
df['total_reviews'].astype('float')

0         375.0
1        2457.0
2        3044.0
3       35882.0
4       28988.0
         ...
2403     1084.0
2404      600.0
2405    12307.0
2406     6091.0
2407     6765.0
Name: total_reviews, Length: 2408, dtype: float64

In [ ]:
df['total_reviews'] = df['total_reviews'].astype('float')

In [ ]:
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [ ]:
df.drop_duplicates()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2403,"UGREEN USB-C Bluetooth Adapter for PS5, Blueto...",4.4,1084.0,2000.0,22.99,29.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61Hd-cVZsz...,https://www.amazon.com/UGREEN-Bluetooth-aptX-A...,2025-08-21 11:32:34,Phones,23.34
2404,Microsoft Surface Pro 2-in-1 Laptop/Tablet (20...,4.4,600.0,300.0,929.00,1199.99,No Badge,Organic,No Coupon,Add to cart,2025-09-02,Energy efficiency,https://m.media-amazon.com/images/I/617kakTyb3...,https://www.amazon.com/Microsoft-Surface-Windo...,2025-08-21 11:32:34,Laptops,22.58
2405,"Sennheiser HD 280 Pro Headphone, Black",4.5,12307.0,1000.0,84.29,84.29,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61+XjHbWrZ...,https://www.amazon.com/Sennheiser-280-Pro-Head...,2025-08-21 11:32:34,Phones,0.00
2406,"Crucial 64GB DDR5 RAM Kit (2x32GB), 4800MHz CL...",4.8,6091.0,500.0,139.96,199.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61O5IUjSDS...,https://www.amazon.com/Crucial-2x32GB-4800MHz-...,2025-08-21 11:32:34,Laptops,30.02
2407,"SABRE 120 dB Wedge Door Stop Security Alarm, E...",4.4,6765.0,2000.0,12.49,14.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61HQzV1nC-...,https://www.amazon.com/SABRE-Wedge-Security-Al...,NaN,NaN,NaN

In [ ]:
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [ ]:
df.sort_values(by = "product_title", ascending = True)

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
1960,2-Pack LR44 Alkaline Button Coin Cell Battery,4.7,14810.0,5000.0,5.35,5.35,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61xOVDKViO...,NaN,2025-08-21 11:29:31,Power & Batteries,0.00
264,"3M N95 Respirator 8511, Cool Flow Valve, 10 Pa...",4.6,15567.0,10000.0,20.53,21.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/71bnz+IFLd...,https://www.amazon.com/3M-8511PB1-Particulate-...,2025-08-21 11:16:50,Other Electronics,6.64
1682,67XL Ink Cartridges Black/Color Combo Pack Rem...,4.4,19278.0,2000.0,29.99,49.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/812qS29OZN...,https://www.amazon.com/Ink-Cartridges-Remanufa...,2025-08-21 11:27:27,Laptops,40.01
1843,8BitDo Pro 3 Bluetooth Controller for Switch/S...,4.2,12.0,1000.0,69.99,69.99,No Badge,Organic,No Coupon,NaN,2025-09-01,NaN,https://m.media-amazon.com/images/I/71DI4hqQ1N...,https://www.amazon.com/8BitDo-Bluetooth-Contro...,2025-08-21 11:28:55,Phones,0.00
1619,8Bitdo Ultimate 2 Bluetooth Controller for Swi...,4.3,6587.0,2000.0,59.99,69.99,No Badge,Organic,No Coupon,NaN,2025-09-01,NaN,https://m.media-amazon.com/images/I/71KEyGBKA5...,https://www.amazon.com/Bluetooth-Controller-Jo...,2025-08-21 11:27:02,Gaming,14.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,myQ Smart Garage Security Camera – 1080p HD Vi...,4.2,5284.0,2000.0,29.22,49.99,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/51Sx6UWyeO...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:22:39,Phones,41.55
1706,myQ Smart Garage Security Camera – 1080p HD Vi...,4.2,5284.0,2000.0,29.22,49.99,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/51Sx6UWyeO...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:27:39,Phones,41.55
89,myQ Smart Garage Security Camera – 1080p HD Vi...,4.2,5284.0,2000.0,29.22,49.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/51Sx6UWyeO...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:15:00,Phones,41.55
2391,"soundcore AeroFit 2 by Anker, Open-Ear Headpho...",4.4,1505.0,1000.0,129.99,129.99,No Badge,Organic,No Coupon,NaN,NaN,Energy efficiency +3 more,https://m.media-amazon.com/images/I/61QmISS++G...,https://www.amazon.com/Soundcore-Open-Ear-Head...,2025-08-21 11:32:34,Laptops,0.00
970,weBoost Drive Reach Overland - Cell Phone Sign...,4.2,2174.0,500.0,549.99,549.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/71poIu6cid...,https://www.amazon.com/weBoost-Drive-Reach-Ove...,2025-08-21 11:22:27,Phones,0.00

In [ ]:
df.sort_values(by = "total_reviews",ascending = True)

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
2115,Dell Pro Dock WD25 - USB Type-C with DP Alt Mo...,5.0,1.0,400.0,164.99,164.99,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/617iBjyibh...,https://www.amazon.com/Dell-Pro-Dock-WD25-Disp...,2025-08-21 11:30:33,Laptops,0.00
785,SanDisk 512GB microSD Express microSD Card - U...,3.5,3.0,2000.0,116.69,116.69,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/81kmAlcUBB...,https://www.amazon.com/SanDisk-512GB-microSD-E...,2025-08-21 11:20:59,Storage,0.00
1238,Poly Studio V12 – USB Video Bar for Small Room...,5.0,3.0,NaN,864.99,864.99,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61k52eeDr0...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:24:36,Cameras,0.00
2029,Dell Pro Thunderbolt 4 Smart Dock SD25TB4 – US...,5.0,4.0,500.0,248.00,297.95,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61bcU5MUbA...,https://www.amazon.com/Dell-Thunderbolt-Smart-...,2025-08-21 11:29:57,Laptops,16.76
1581,"RCA 10.1"" WiFi Digital Picture Frame Uhale App...",4.0,5.0,NaN,59.99,79.99,No Badge,Sponsored,No Coupon,NaN,2025-09-01,NaN,https://m.media-amazon.com/images/I/71yebnw2SU...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:26:50,Storage,25.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,"Amazon Basics HDMI Cable, 3ft, 4K@60Hz, High-S...",4.7,553927.0,10000.0,5.99,5.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/81AxKWgSaK...,https://www.amazon.com/AmazonBasics-High-Speed...,2025-08-21 11:20:11,Chargers & Cables,0.00
17,Amazon Basics AAA Alkaline High-Performance Ba...,4.7,625776.0,100000.0,14.49,14.49,Best Seller,Organic,No Coupon,Add to cart,2025-08-29,Safer chemicals +1 more,https://m.media-amazon.com/images/I/81Apg8B6+0...,https://www.amazon.com/Amazon-Basics-AAA-High-...,2025-08-21 11:14:29,Laptops,0.00
10,Amazon Basics 48-Pack AA Alkaline High-Perform...,4.7,865598.0,100000.0,14.99,14.99,Best Seller,Organic,No Coupon,Add to cart,2025-08-29,Safer chemicals +1 more,https://m.media-amazon.com/images/I/81iJ+tnLAD...,https://www.amazon.com/AmazonBasics-Performanc...,2025-08-21 11:14:29,Laptops,0.00
854,Buffalo Games - Gold - Eric Dowdle - Golden Ga...,NaN,NaN,50.0,12.00,12.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/81IhN+yhrY...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:21:25,Other Electronics,0.00
1857,"Lenovo ThinkPad X1 Carbon Gen 13 Aura Edition,...",NaN,NaN,200.0,2098.00,2549.00,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61JZTWfKMR...,https://www.amazon.com/Lenovo-ThinkPad-Carbon-...,2025-08-21 11:28:55,Laptops,17.69

In [ ]:
df.sort_values(by = ["total_reviews","original_price"],ascending = [True,False])

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
2115,Dell Pro Dock WD25 - USB Type-C with DP Alt Mo...,5.0,1.0,400.0,164.99,164.99,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/617iBjyibh...,https://www.amazon.com/Dell-Pro-Dock-WD25-Disp...,2025-08-21 11:30:33,Laptops,0.00
1238,Poly Studio V12 – USB Video Bar for Small Room...,5.0,3.0,NaN,864.99,864.99,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61k52eeDr0...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:24:36,Cameras,0.00
785,SanDisk 512GB microSD Express microSD Card - U...,3.5,3.0,2000.0,116.69,116.69,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/81kmAlcUBB...,https://www.amazon.com/SanDisk-512GB-microSD-E...,2025-08-21 11:20:59,Storage,0.00
2029,Dell Pro Thunderbolt 4 Smart Dock SD25TB4 – US...,5.0,4.0,500.0,248.00,297.95,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61bcU5MUbA...,https://www.amazon.com/Dell-Thunderbolt-Smart-...,2025-08-21 11:29:57,Laptops,16.76
87,"RCA 10.1"" WiFi Digital Picture Frame Uhale App...",4.0,5.0,NaN,59.99,79.99,No Badge,Sponsored,No Coupon,NaN,2025-09-01,NaN,https://m.media-amazon.com/images/I/71yebnw2SU...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:15:00,Storage,25.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,"Amazon Basics HDMI Cable, 3ft, 4K@60Hz, High-S...",4.7,553927.0,10000.0,5.99,5.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/81AxKWgSaK...,https://www.amazon.com/AmazonBasics-High-Speed...,2025-08-21 11:20:11,Chargers & Cables,0.00
17,Amazon Basics AAA Alkaline High-Performance Ba...,4.7,625776.0,100000.0,14.49,14.49,Best Seller,Organic,No Coupon,Add to cart,2025-08-29,Safer chemicals +1 more,https://m.media-amazon.com/images/I/81Apg8B6+0...,https://www.amazon.com/Amazon-Basics-AAA-High-...,2025-08-21 11:14:29,Laptops,0.00
10,Amazon Basics 48-Pack AA Alkaline High-Perform...,4.7,865598.0,100000.0,14.99,14.99,Best Seller,Organic,No Coupon,Add to cart,2025-08-29,Safer chemicals +1 more,https://m.media-amazon.com/images/I/81iJ+tnLAD...,https://www.amazon.com/AmazonBasics-Performanc...,2025-08-21 11:14:29,Laptops,0.00
1857,"Lenovo ThinkPad X1 Carbon Gen 13 Aura Edition,...",NaN,NaN,200.0,2098.00,2549.00,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61JZTWfKMR...,https://www.amazon.com/Lenovo-ThinkPad-Carbon-...,2025-08-21 11:28:55,Laptops,17.69
854,Buffalo Games - Gold - Eric Dowdle - Golden Ga...,NaN,NaN,50.0,12.00,12.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/81IhN+yhrY...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:21:25,Other Electronics,0.00

In [ ]:
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [ ]:
df['product_category'].value_counts()

product_category
Laptops                502
Phones                 428
Other Electronics      378
TV & Display           217
Cameras                201
Power & Batteries      201
Chargers & Cables      113
Storage                 94
Speakers                86
Networking              49
Printers & Scanners     34
Headphones              31
Smart Home              31
Gaming                  28
Wearables               14
Name: count, dtype: int64

In [ ]:
df['product_category'].value_counts()

product_category
Laptops                502
Phones                 428
Other Electronics      378
TV & Display           217
Cameras                201
Power & Batteries      201
Chargers & Cables      113
Storage                 94
Speakers                86
Networking              49
Printers & Scanners     34
Headphones              31
Smart Home              31
Gaming                  28
Wearables               14
Name: count, dtype: int64

In [ ]:
df.groupby(['product_category'])

In [ ]:
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [ ]:
df.groupby(['product_rating'])['product_category'].mean

In [ ]:
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [ ]:
df[(df['total_reviews']  > 500) & (df['purchased_last_month'] > 1000)]

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00
5,Texas Instruments TI-84 Plus CE Color Graphing...,4.6,44522.0,100000.0,99.95,99.95,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71AyPChhFd...,https://www.amazon.com/Texas-Instruments-TI-84...,2025-08-21 11:14:29,Other Electronics,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2379,"Duracell Coppertop 9V Battery, 6 Count (Pack o...",4.8,5207.0,20000.0,25.47,25.47,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61ZSfHGJ2b...,NaN,2025-08-21 11:32:34,Power & Batteries,0.00
2386,"UBeesize Phone Tripod Pro S, Premium Flexible ...",4.4,30950.0,3000.0,12.47,14.50,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61SWwP8aS0...,https://www.amazon.com/UBeesize-Phone-Tripod-W...,2025-08-21 11:32:34,Phones,14.00
2389,"Scosche BTFM9 FM Bluetooth Transmitter Car, Du...",4.2,2242.0,2000.0,19.99,24.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61Dy418jzg...,https://www.amazon.com/Scosche-Bluetooth-Trans...,2025-08-21 11:32:34,Chargers & Cables,20.01
2403,"UGREEN USB-C Bluetooth Adapter for PS5, Blueto...",4.4,1084.0,2000.0,22.99,29.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61Hd-cVZsz...,https://www.amazon.com/UGREEN-Bluetooth-aptX-A...,2025-08-21 11:32:34,Phones,23.34
2407,"SABRE 120 dB Wedge Door Stop Security Alarm, E...",4.4,6765.0,2000.0,12.49,14.99,No Badge,Organic,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61HQzV1nC-...,https://www.amazon.com/SABRE-Wedge-Security-Al...,NaN,NaN,NaN

In [ ]:
df['valuable'] = 'No'
df.loc[(df['total_reviews'] > 500) & (df['purchased_last_month'] > 1000), "valuable"] = "yes"

In [ ]:
df['valuable'].value_counts()

valuable
No     1336
yes    1072
Name: count, dtype: int64