In [2]:
import pandas as pd

In [6]:
pd.read_csv(r"/content/annual-enterprise-survey-2025-financial-year-provisional.csv")

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [10]:
df = pd.read_csv(r"/content/annual-enterprise-survey-2025-financial-year-provisional.csv")

In [11]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [12]:
df.head(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
5,2025,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,67376,ANZSIC06 divisions A-S (excluding classes K633...
6,2025,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,9483,ANZSIC06 divisions A-S (excluding classes K633...
7,2025,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,33337,ANZSIC06 divisions A-S (excluding classes K633...
8,2025,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,160833,ANZSIC06 divisions A-S (excluding classes K633...
9,2025,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,455,ANZSIC06 divisions A-S (excluding classes K633...

In [13]:
df.tail()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60255 entries, 0 to 60254
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         60255 non-null  int64
 1   Industry_aggregation_NZSIOC  60255 non-null  object
 2   Industry_code_NZSIOC         60255 non-null  object
 3   Industry_name_NZSIOC         60255 non-null  object
 4   Units                        60255 non-null  object
 5   Variable_code                60255 non-null  object
 6   Variable_name                60255 non-null  object
 7   Variable_category            60255 non-null  object
 8   Value                        60255 non-null  object
 9   Industry_code_ANZSIC06       60255 non-null  object
dtypes: int64(1), object(9)
memory usage: 4.6+ MB

In [18]:
df.iloc[0:4,0:5]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units
0,2025,Level 1,99999,All industries,Dollars (millions)
1,2025,Level 1,99999,All industries,Dollars (millions)
2,2025,Level 1,99999,All industries,Dollars (millions)
3,2025,Level 1,99999,All industries,Dollars (millions)

In [20]:
df.shape

(60255, 10)

In [21]:
df.columns

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [25]:
df.loc[0:3,"Year":"Industry_code_NZSIOC"]

   Year Industry_aggregation_NZSIOC Industry_code_NZSIOC
0  2025                     Level 1                99999
1  2025                     Level 1                99999
2  2025                     Level 1                99999
3  2025                     Level 1                99999

In [26]:
df.iloc[0:5,0:6]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code
0,2025,Level 1,99999,All industries,Dollars (millions),H01
1,2025,Level 1,99999,All industries,Dollars (millions),H04
2,2025,Level 1,99999,All industries,Dollars (millions),H05
3,2025,Level 1,99999,All industries,Dollars (millions),H07
4,2025,Level 1,99999,All industries,Dollars (millions),H08

In [27]:
df.iloc[0:-1,0:-1]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750
...,...,...,...,...,...,...,...,...,...
60249,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H36,Current ratio,Financial ratios,91
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5

In [28]:
df.isnull().sum()

Year                           0
Industry_aggregation_NZSIOC    0
Industry_code_NZSIOC           0
Industry_name_NZSIOC           0
Units                          0
Variable_code                  0
Variable_name                  0
Variable_category              0
Value                          0
Industry_code_ANZSIC06         0
dtype: int64

In [29]:
df.dropna()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [32]:
df.dropna()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [34]:
df.fillna(0)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [40]:
df['Industry_code_NZSIOC'].astype('float')

ValueError: could not convert string to float: 'AA'

In [41]:
df.drop_duplicates()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [47]:
df.sort_values(by=['Year','Value'],ascending = True)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
56472,2013,Level 3,CC41,Printing,Percentage,H40,Return on total assets,Financial ratios,-1,ANZSIC06 groups C161 and C162
56508,2013,Level 4,CC411,Printing,Percentage,H40,Return on total assets,Financial ratios,-1,ANZSIC06 groups C161 and C162
56893,2013,Level 3,CC71,Primary Metal and Metal Product Manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,"-131,300","ANZSIC06 groups C211, C212, C213, and C214"
56929,2013,Level 4,CC711,Primary Metal and Metal Product Manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,"-131,300","ANZSIC06 groups C211, C212, C213, and C214"
56399,2013,Level 3,CC32,"Pulp, Paper and Converted Paper Product Manufa...",Percentage,H39,Return on equity,Financial ratios,-17,ANZSIC06 groups C151 and C152
...,...,...,...,...,...,...,...,...,...,...
4450,2025,Level 4,RS113,Gambling Activities,Dollars (millions),H20,Non-operating expenses,Financial performance,C,ANZSIC06 group R920
4461,2025,Level 4,RS113,Gambling Activities,Dollars (millions),H31,Shareholders funds or owners equity,Financial position,C,ANZSIC06 group R920
4463,2025,Level 4,RS113,Gambling Activities,Dollars (millions),H33,Other liabilities,Financial position,C,ANZSIC06 group R920
4468,2025,Level 4,RS113,Gambling Activities,Percentage,H39,Return on equity,Financial ratios,C,ANZSIC06 group R920
4470,2025,Level 4,RS113,Gambling Activities,Percentage,H41,Liabilities structure,Financial ratios,C,ANZSIC06 group R920

In [43]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [49]:
df['Industry_aggregation_NZSIOC'].value_counts()

Industry_aggregation_NZSIOC
Level 4    32981
Level 3    20007
Level 1     7267
Name: count, dtype: int64

In [52]:
df.groupby(['Industry_name_NZSIOC'])

In [57]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [56]:
df.groupby(['Industry_name_NZSIOC'])["Value"].mean()

TypeError: agg function failed [how->mean,dtype->object]